sudo: required
services:
  - docker

before_install:
  - docker build -t sghabi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sghabi/react-test npm run test -- --watchAll=false

after_success:
  - docker build -t sghabi/multi-client ./client
  - docker build -t sghabi/multi-nginx ./nginx
  - docker build -t sghabi/multi-server ./server
  - docker build -t sghabi/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push sghabi/multi-client
  - docker push sghabi/multi-nginx
  - docker push sghabi/multi-server
  - docker push sghabi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-940142806974
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
